use std::{
    fs,
    sync::Arc,
    time::{SystemTime, UNIX_EPOCH},
};

#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;

use camino::{Utf8Path, Utf8PathBuf};
use rloc_core::{
    AnalysisWarning, Analyzer, BackendFileAnalysis, ClassificationOptions, FileCategory,
    FileMetrics, Language, LanguageBackend, LanguageBackendRegistry, LanguageDescriptor,
    LineExplanation, ScanOptions, categories,
};

#[derive(Debug, Clone)]
struct TestRustBackend {
    fail_path_suffix: Option<Arc<str>>,
}

impl TestRustBackend {
    fn healthy() -> Self {
        Self {
            fail_path_suffix: None,
        }
    }

    fn fail_on(path_suffix: &str) -> Self {
        Self {
            fail_path_suffix: Some(Arc::from(path_suffix)),
        }
    }
}

impl LanguageBackend for TestRustBackend {
    fn descriptor(&self) -> LanguageDescriptor {
        LanguageDescriptor::new(Language::Rust, "Rust", &["rs"])
    }

    fn classify_file(
        &self,
        path: &Utf8Path,
        category: FileCategory,
        _options: &ClassificationOptions,
    ) -> Result<BackendFileAnalysis, String> {
        if self
            .fail_path_suffix
            .as_deref()
            .is_some_and(|suffix| path.as_str().ends_with(suffix))
        {
            return Err("simulated backend read failure".to_owned());
        }

        let bytes = fs::read(path.as_std_path()).map_err(|error| error.to_string())?;
        let contents = String::from_utf8_lossy(&bytes);
        let total_lines = contents.lines().count() as u32;
        let blank_lines = contents
            .lines()
            .filter(|line| line.trim().is_empty())
            .count() as u32;
        let code_lines = total_lines - blank_lines;

        Ok(BackendFileAnalysis {
            metrics: FileMetrics::from_line_breakdown(
                path.to_path_buf(),
                Language::Rust,
                category,
                bytes.len() as u64,
                total_lines,
                blank_lines,
                code_lines,
                0,
                0,
                0,
                0,
            ),
            line_explanations: vec![LineExplanation {
                line_number: 1,
                kind: "code".to_owned(),
                snippet: contents.lines().next().unwrap_or_default().to_owned(),
                reason: "test backend treats non-empty lines as code".to_owned(),
            }],
            warnings: vec![AnalysisWarning::for_language(
                Language::Rust,
                "test backend executed",
            )],
        })
    }
}

#[test]
fn generated_header_marks_file_as_generated() {
    let root = temp_workspace("generated_header_marks_file_as_generated");
    let generated = root.join("src/service.rs");
    write_file(
        &root,
        "src/service.rs",
        "// Code generated by test fixture. DO NOT EDIT.\nfn generated() {}\n",
    );

    assert_eq!(
        categories::detect_category(&generated),
        FileCategory::Generated
    );

    cleanup_workspace(&root);
}

#[test]
fn unreadable_file_becomes_warning_instead_of_aborting_scan() {
    let root = temp_workspace("unreadable_file_becomes_warning_instead_of_aborting_scan");
    write_file(&root, "src/ok.rs", "fn ok() {}\n");
    write_file(&root, "src/broken.rs", "fn broken() {}\n");

    let analyzer = Analyzer::new(
        LanguageBackendRegistry::new().with_backend(TestRustBackend::fail_on("src/broken.rs")),
    );

    let report = analyzer.scan(&root, &ScanOptions::default()).unwrap();

    assert_eq!(report.files.len(), 1);
    assert_eq!(report.files[0].path, root.join("src/ok.rs"));
    assert_eq!(report.summary.files, 1);
    assert!(
        report
            .warnings
            .iter()
            .any(|warning| warning.path.as_ref() == Some(&root.join("src/broken.rs")))
    );

    cleanup_workspace(&root);
}

#[test]
fn custom_exclude_patterns_still_apply_after_builtin_filters() {
    let root = temp_workspace("custom_exclude_patterns_still_apply_after_builtin_filters");
    write_file(&root, "src/lib.rs", "fn main() {}\n");
    write_file(&root, "generated/out.rs", "fn generated() {}\n");

    let files = rloc_core::discover::collect_candidate_files(
        &root,
        &ScanOptions {
            exclude_patterns: vec!["**/generated/**".to_owned()],
            ..ScanOptions::default()
        },
    )
    .unwrap();

    assert_eq!(files, vec![root.join("src/lib.rs")]);

    cleanup_workspace(&root);
}

#[test]
fn vendor_and_generated_signals_are_exposed_for_explain() {
    let root = temp_workspace("vendor_and_generated_signals_are_exposed_for_explain");
    let generated = root.join("src/client.rs");
    let vendor = root.join("vendor/lib.rs");
    write_file(
        &root,
        "src/client.rs",
        "// @generated by fixture\nfn generated_client() {}\n",
    );
    write_file(&root, "vendor/lib.rs", "fn vendored() {}\n");

    let analyzer =
        Analyzer::new(LanguageBackendRegistry::new().with_backend(TestRustBackend::healthy()));

    let generated_report = analyzer.explain(&generated).unwrap();
    assert_eq!(generated_report.category, FileCategory::Generated);
    assert!(
        generated_report
            .reasons
            .iter()
            .any(|reason| reason.contains("generated"))
    );

    let vendor_report = analyzer.explain(&vendor).unwrap();
    assert_eq!(vendor_report.category, FileCategory::Vendor);
    assert!(
        vendor_report
            .reasons
            .iter()
            .any(|reason| reason.contains("vendor"))
    );

    cleanup_workspace(&root);
}

#[cfg(unix)]
#[test]
fn unreadable_directory_becomes_warning_instead_of_aborting_scan_and_detect() {
    let root = temp_workspace("unreadable_directory_becomes_warning_instead_of_aborting_scan");
    write_file(&root, "src/ok.rs", "fn ok() {}\n");
    write_file(&root, "blocked/secret.rs", "fn secret() {}\n");

    let blocked_dir = root.join("blocked");
    fs::set_permissions(blocked_dir.as_std_path(), fs::Permissions::from_mode(0o000)).unwrap();

    let analyzer =
        Analyzer::new(LanguageBackendRegistry::new().with_backend(TestRustBackend::healthy()));

    let result = (|| {
        let scan = analyzer.scan(&root, &ScanOptions::default()).unwrap();
        assert_eq!(scan.files.len(), 1);
        assert_eq!(scan.files[0].path, root.join("src/ok.rs"));
        assert!(scan.warnings.iter().any(|warning| {
            warning.message.contains("blocked") && warning.message.contains("Permission denied")
        }));

        let detect = analyzer.detect(&root, &ScanOptions::default()).unwrap();
        assert_eq!(detect.languages, vec![Language::Rust]);
        assert!(detect.warnings.iter().any(|warning| {
            warning.message.contains("blocked") && warning.message.contains("Permission denied")
        }));
    })();

    fs::set_permissions(blocked_dir.as_std_path(), fs::Permissions::from_mode(0o755)).unwrap();
    cleanup_workspace(&root);
    result
}

fn temp_workspace(test_name: &str) -> Utf8PathBuf {
    let unique = format!(
        "rloc-core-{test_name}-{}-{}",
        std::process::id(),
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    );
    let path = std::env::temp_dir().join(unique);
    fs::create_dir_all(&path).unwrap();
    Utf8PathBuf::from_path_buf(path).unwrap()
}

fn write_file(root: &Utf8Path, relative: &str, contents: &str) {
    let path = root.join(relative);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent.as_std_path()).unwrap();
    }
    fs::write(path.as_std_path(), contents).unwrap();
}

fn cleanup_workspace(root: &Utf8Path) {
    if root.exists() {
        fs::remove_dir_all(root.as_std_path()).unwrap();
    }
}
